mysql status 2

diff --git a/.github/workflows/pull-request-check.yml b/.github/workflows/pull-request-check.yml
--- a/.github/workflows/pull-request-check.yml
+++ b/.github/workflows/pull-request-check.yml
@@ -13,7 +13,6 @@ jobs:
           sudo apt install python3 python3-pip tree -y
           pip install --upgrade pip
           pip install -r requirements.txt
-#          sudo systemctl start mysql
           systemctl status mysql
       - name: healthz-check
         run: |
@@ -27,5 +26,14 @@ jobs:
             exit 1
           else
             echo "SUCCESS"
-            kill -9 `lsof -i:8080 -t`
           fi
+
+#      - name: Failure sudo systemctl start mysql
+#        if: `curl  -w "%{http_code}" http://localhost:8080/healthz` == '503'
+#        run: exit 1
+#      - name: Sucsess
+#        if: `curl  -w "%{http_code}" http://localhost:8080/healthz` == '200'
+#        run: |
+#          echo "Sucsess"
+#          sleep 5
+#          kill -9 `lsof -i:8080 -t`
